### ISSUE TITLE
`plyv` fails on the given example

### ISSUE THREAD

**Issue by ThisIsIsaac** [roboception/cvkit#13]
When running `plyv 1097_disp.pfm *param.txt`, I get:

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  33
  Current serial number in output stream:  34
```

Other examples work as expected:
- `plycmd 1097_disp.pfm -out 1097.ply`
- `sv 1097_disp.pfm 1097_rgb.ppm` 

## system info

CentOS7 -> MacOS Catalina (with `ssh -X`)

**Comment by heikohimu** [comment]
ssh -X cannot forward 3D stuff, e.g. OpenGL. Thats why plyv fails.
