### ISSUE TITLE
compile error on ubuntu16 kernel4.15 g++8

### ISSUE THREAD

**Issue by littlewhite428** [roboception/cvkit#17]
## Environment
Ubuntu 16.04
kernel 4.15
g++ 8.4
## Error
when i run `make`
 
>/cvkit/gimage/gdal_io.cc:446:5: error: ‘GDALRasterIOExtraArg’ was not declared in this scope
     GDALRasterIOExtraArg arg;

> cvkit/cvkit/gimage/gdal_io.cc:447:5: error: there are no arguments to ‘INIT_RASTERIO_EXTRA_ARG’ that depend on a template parameter, so a declaration of ‘INIT_RASTERIO_EXTRA_ARG’ must be available [-fpermissive]
     INIT_RASTERIO_EXTRA_ARG(arg)

> /cvkit/cvkit/gimage/gdal_io.cc:447:32: error: ‘INIT_RASTERIO_EXTRA_ARG’ was not declared in this scope
     INIT_RASTERIO_EXTRA_ARG(arg);

**Comment by heikohimu** [comment]
It fails because the GDAL version that you are using is too old (i.e. < 2.0). Please note that Ubuntu 16.04 reached end of life about half a year ago and is therefore not supported any more.

You can turn off compiling with GDAL support by calling cmake with the parameter '-D USE_GDAL=OFF'.

**Comment by littlewhite428** [comment]
Thank you for your answer! Looks like I'm going to upgrade my operating system.
