### ISSUE TITLE
Memory leakage in View::setCamera

### ISSUE THREAD

**Issue by csukuangfj** [roboception/cvkit#2]
Please refer to <https://github.com/roboception/cvkit/blob/master/gimage/view.cc#L89>

```.cpp
void View::setCamera(const gmath::Camera *c)
{
  if (c == 0)
  {
    camera=0;
    return;
  }

```
If `c` is zero,  `camera` is set to 0 manually. The memory is leaked here if `camera` was not NULL.

**Comment by heikohimu** [comment]
True, I will fix that. Thanks!
