### ISSUE TITLE
Textures in plyv

### ISSUE THREAD

**Issue by davidhesselbom** [roboception/cvkit#4]
In your [2014 paper](http://www.cs.middlebury.edu/~schar/papers/datasets-gcpr2014.pdf), the top, left-most image in figure 1 appears to show plyv using one of the "im#.png" images as a texture. 

I'm struggling to get this to work. Do you think you could provide the complete console command, with all parameters necessary to get plyv to do this, assuming I already have the files in the [dataset](http://vision.middlebury.edu/stereo/submit3/zip/MiddEval3-data-Q.zip)?

**Comment by heikohimu** [comment]
It works like this:
plyv disp0GT.pfm,i=im0.png

**Comment by davidhesselbom** [comment]
That did it, thanks a lot! I must have made a mistake with spaces between the parameters or something.
