### ISSUE TITLE
how to read .pfm file

### ISSUE THREAD

**Issue by 2h4dl** [roboception/cvkit#5]
I write a code to read a pfm file and then to create a depth map,
but the depth map is totally different with the one generated by sv.

```
def read_calib(calib_file_path):
    with open(calib_file_path, 'r') as calib_file:
        calib = {}
        csv_reader = csv.reader(calib_file, delimiter='=')
        for attr, value in csv_reader:
            calib.setdefault(attr, value)

    return calib


def read_pfm(pfm_file_path):
    with open(pfm_file_path, 'rb') as pfm_file:
        header = pfm_file.readline().decode().rstrip()
        channels = 3 if header == 'PF' else 1

        dim_match = re.match(r'^(\d+)\s(\d+)\s$', pfm_file.readline().decode()
        if dim_match:
            width, height = map(int, dim_match.groups())
        else:
            raise Exception("Malformed PFM header.")

        scale = float(pfm_file.readline().decode().rstrip())
        if scale < 0:
            endian = '<' # littel endian
            scale = -scale
        else:
            endian = '>' # big endian

        dispariy = np.fromfile(pfm_file, endian + 'f') / scale

    return dispariy, [(height, width, channels), scale]


def create_depth_map(pfm_file_path, calib=None):

    dispariy, [shape,scale] = read_pfm(pfm_file_path)

    if calib is None:
        raise Exception("Loss calibration information.")
    else:
        fx = float(calib['cam0'].split(' ')[0].lstrip('['))

        base_line = float(calib['baseline'])
        doffs = float(calib['doffs'])

        depth_map = fx*base_line / (dispariy + doffs)

        depth_map = np.reshape(depth_map, newshape=shape)

        depth_map = np.flipud(depth_map).astype('uint8')

        return depth_map
```

![](https://i.loli.net/2019/04/10/5cadad2b05592.jpg)
<center>disparity map</center>⬆

![](https://i.loli.net/2019/04/10/5cada6facc5f5.jpg)
<center>depth map</center>⬆

![](https://i.loli.net/2019/04/10/5cadbfa1ecfff.png)
generated by sv⬆

**Comment by heikohimu** [comment]
With sv, you see the disparity values. Bright means high disparity, which means close to the camera. After converting disparity to depth, bright means far away. So, I do not see the problem here.

**Comment by 2h4dl** [comment]
Thanks @heikohimu . I'm new to stereo vision.  You've just cleared up some of my doubts.
Another question, what's the meaning of scale factor or what did it do except to tell endianness, thanks again.

**Comment by heikohimu** [comment]
That is just a feature that the PFM format supports. It is meant as a global scale factor for all float values. It is not used for disparity images.

**Comment by qiuweibo** [comment]
Hi, 

I use similar code above to read .pfm file and get some depth value as infinity:

`def read_pfm2(file):
        # Adopted from https://stackoverflow.com/questions/48809433/read-pfm-format-in-python
        with open(file, "rb") as f:
            # Line 1: PF=>RGB (3 channels), Pf=>Greyscale (1 channel)
            type = f.readline().decode('latin-1')
            if "PF" in type:
                channels = 3
                print("Channels: 3")
            elif "Pf" in type:
                channels = 1
                print("Channels: 1")
            else:
                print("ERROR: Not a valid PFM file")
                sys.exit(1)
            # Line 2: width height
            line = f.readline().decode('latin-1')
            width, height = re.findall('\d+', line)
            width = int(width)
            height = int(height)

            # Line 3: +ve number means big endian, negative means little endian
            line = f.readline().decode('latin-1')
            BigEndian = True
            if "-" in line:
                BigEndian = False
            # Slurp all binary data
            samples = width * height * channels;
            buffer = f.read(samples * 4)
            # Unpack floats with appropriate endianness
            if BigEndian:
                fmt = ">"
            else:
                fmt = "<"
            fmt = fmt + str(samples) + "f"
            img = unpack(fmt, buffer)
        return img, height, width`

img contains the disparity value, some of which are infinity. Any idea would be appreciated!

**Comment by heikohimu** [comment]
Infinity is normally used for invalid disparities.
