### ISSUE TITLE
plycmd

### ISSUE THREAD

**Issue by MotamedNia** [roboception/cvkit#6]
Hi, thanks for your works. I had a problem with plycmd. I want to know how it convert a pfm to ply?
In my pfm file "z" points coordinate range are approximately between 7000 and 9000 but in made ply file with plycmd range of z values are approximately between 9000 and 12000.

**Comment by heikohimu** [comment]
The conversion from a (disparity image) in pfm format into a (3D model) in ply format depends on parameters that are stored in a separate parameter text file. This is basically explained here: 

https://github.com/roboception/cvkit/blob/master/USAGE.md#loading-disparity-images-as-3d-model

If you post your parameter file, then I can also explain it.

**Comment by MotamedNia** [comment]
This is my parameter file
```
camera.A=[1000 0 256; 0 1000 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[-1 0 0; 0 -1 0; 0 0 -1]
camera.T=[0 0 0]

rho=1000000
```
In fact I used blender to generate synthetic image
The image generated with these parameters
```
[intrinsics]
focal_length_mm = 100.0
image_resolution_x_px = 512
image_resolution_y_px = 512
sensor_size_mm = 35.0
fstop = 100.0

[extrinsics]
num_cams_x = 3
num_cams_y = 1
baseline_mm = 100.0
focus_distance_m = 8.0
```

**Comment by heikohimu** [comment]
Ok, I understand. Is the image that you generate a disparity or a depth image, i.e. are the values of the image inverse depth or depth? plycmd expects disparity images. It will not work with depth images without changing the source code. So, I assume that you have a disparity image for now.

I see two mistakes in the parameter file:

Firstly, the focal length is much too big. A 35 mm (full format) sensor has a chip size of 36 mm x 24 mm (which is actually not square as your specified image size). If I assume that the image width of 512 pixels corresponds to 36 mm, then the focal length in pixel would be 36 mm / 100 mm * 512 pixel = 184.32 pixel.

Secondly, a rotation matrix must have det(R)=1. Your rotation matrix has det == -1, which means that it also mirrors all points. I would suggest using the identity matrix as long as you do not need to visualize multiple models from different poses at the same time.

I would suggest using:

```
camera.A=[184.32 0 256; 0 184.32 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[1 0 0; 0 1 0; 0 0 1]
camera.T=[0 0 0]

rho=18432
```

**Comment by MotamedNia** [comment]
I have both depth and disparity images. Check both with sv command and seems both are correct images( depth image has lower z values for closer pixels to camera and disparity is inverse). I don't know why but plycmd don't create any reasonable results from diparity images. So I used depth images and I set det=-1 to mirrors all points. I am checking all results with meshlab. 
I tested your suggested parameter but again results are not in range and also the 3d model has been shrunk.

**Comment by heikohimu** [comment]
Ok, can you post a sample disparity image. Then I could have a look.

**Comment by MotamedNia** [comment]
[disp_depth.zip](https://github.com/roboception/cvkit/files/3277253/disp_depth.zip)

**Comment by MotamedNia** [comment]
I  post both depth and disparity images which I used

**Comment by heikohimu** [comment]
I found out what is wrong. Your disparity image has negative disparities, which means that the optical axis of the virtual stereo setup is not parallel, i.e. it does not correspond to a "standard" stereo setup. The background has a disparity of -18.2857, which actually must be 0. So, I added this value to all values to correct for verging and then invalidated all disparities <= 0, i.e. the background, with this command:

`imgcmd disp.pfm -add 18.2857 -valid 0.001 256 -out disp2.pfm`

Then, I noticed that the focal length must be wrong. I calculated it backwards from the assumption that the focus plane is at 8000 mm (i.e. focus_distance_m = 8.0) and that this was set to 0 disparity, which becomes 18.2857 after adding this value. The relationship is z=f*t/d, which results in f = 8000 mm * 18.2857 pixel  / 100 mm = 1462.9 pixel. Thus, change the parameter file to:

```
camera.A=[1462.9 0 256; 0 1462.9 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[1 0 0; 0 1 0; 0 0 1]
camera.T=[0 0 0]

rho=146290
```

Opening this with `plyv disp2.pfm,p=param.txt` gives you a nice bunny!

I think you should try configuring blender to not verge the stereo camera, e.g. focus at infinity. Then, a lot of calculations can be avoided.

**Comment by MotamedNia** [comment]
I am very thankful you are considering my problem. Comprehensive solution :)

**Comment by MotamedNia** [comment]
Another question ... is it possible to create a disparity `pfm` from a 3d model `ply` using  `plycmd`?

**Comment by heikohimu** [comment]
No sorry, this is not implemented.
