### ISSUE TITLE
camera rotation  plyv

### ISSUE THREAD

**Issue by MotamedNia** [roboception/cvkit#7]
Hi, I used these parameters for a specific pfm file and used `plyv` tool to view 3D model.
But in all situations the output of `plyv`  is same. I expect to see the model in different view
when the camera rotation matrix change.
These are my parameter files:
```
camera.A=[1462.8572 0 256; 0 1462.8572 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[1 0 0;0 1 0;0 0 1]
camera.T=[0 0 0]


rho=146285.72
```

```
camera.A=[1462.8572 0 256; 0 1462.8572 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[-0.9491587281227112 0.1123562604188919 -0.2940641045570374 ; 0.1094790473580360 0.9936415553092957 0.0262828860431910 ; 0.2951473593711853 -0.0072472877800465 -0.9554242491722107 ]
camera.T=[0 0 0]


rho=146285.72
```

```
camera.A=[1462.8572 0 256; 0 1462.8572 256; 0 0 1]
camera.height=512
camera.width=512

camera.R=[0.9853811860084534 0.0000000861447589 -0.1703641712665558; -0.1123563423752785 -0.7516981959342957 -0.6498660445213318;-0.1280625015497208 0.6595072746276855 -0.7407092452049255]
camera.T=[0 0 0]


rho=146285.72
```
And also I upload the pfm and texture files:
[bunny.zip](https://github.com/roboception/cvkit/files/3342765/bunny.zip)

Thank you for your consideration,

**Comment by heikohimu** [comment]
When loading a model, plyv tries to position the virtual camera so that the whole scene is seen. It basically ignores the transformation of the parameter file. However, if you load several models into plyv, it uses the transformation to correctly position the individual models towards each other.

**Comment by MotamedNia** [comment]
Thank you for the response
